version: '3.1'

services:

  valuation-app:
    restart: always
    container_name: 'valuation-app'
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "80:80"
      - "443:443"
